# Generated by Django 2.2.5 on 2021-02-09 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('p_title', models.CharField(max_length=100, verbose_name='글 제목')),
                ('p_contents', models.CharField(max_length=300, verbose_name='글 내용')),
                ('p_date', models.DateTimeField(verbose_name='글 작성일')),
                ('p_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
